import {
  MdRocketLaunch,
  MdSync,
  MdTaskAlt,
  MdPrecisionManufacturing,
  MdLocalShipping,
  MdDoneAll,
  MdFileDownload,
} from "react-icons/md";


export const statusData = [
  {
    key: "open",
    name: "Open",
    color: "#64748b",
    icon: <MdRocketLaunch />,
    count: 120,
    total: 1860,
    orders: 80,
    warranty: 40,
  },
  {
    key: "in_process",
    name: "In Process",
    color: "#3b82f6",
    icon: <MdSync />,
    count: 340,
    total: 1860,
    orders: 200,
    warranty: 140,
  },
  {
    key: "file_ready",
    name: "File Ready",
    color: "#06b6d4",
    icon: <MdTaskAlt />,
    count: 210,
    total: 1860,
    orders: 150,
    warranty: 60,
  },
  {
    key: "in_production",
    name: "In Production",
    color: "#8b5cf6",
    icon: <MdPrecisionManufacturing />,
    count: 480,
    total: 1860,
    orders: 300,
    warranty: 180,
  },
  {
    key: "ready_to_ship",
    name: "Ready to Ship",
    color: "#f59e0b",
    icon: <MdLocalShipping />,
    count: 150,
    total: 1860,
    orders: 100,
    warranty: 50,
  },
  {
    key: "shipped",
    name: "Shipped",
    color: "#10b981",
    icon: <MdDoneAll />,
    count: 560,
    total: 1860,
    orders: 400,
    warranty: 160,
  },
];